In [48]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import psycopg2
import sqlalchemy as sa
from   sqlalchemy.engine import URL
from   sqlalchemy import text

In [34]:
url_server = URL.create(
    "postgresql",
    host = 'localhost',
    database = 'postgres',
    username = 'postgres',
    port = 5433,
    password  = '12345')

con = sa.create_engine(url_server).connect()

In [52]:
drivers = pd.read_csv("data_clean/drivers.csv")
qualifying = pd.read_csv("data_raw/qualifying.csv")
#results = pd.read_csv("data_raw/results.csv")

In [53]:
# Clean drivers table
#display(drivers)
drivers.dtypes

# drivers["number"] = drivers["number"].replace(["\\N"], [np.nan])
# drivers["number"] = pd.to_numeric(drivers["number"])

# drivers["code"] = drivers["code"].replace(["\\N"], [np.nan])
#drivers["dob"] = pd.to_datetime(drivers["dob"], format="%Y-%m-%d")

# drivers = drivers[["driverId", "driverRef", "number", "code", "forename", "surname", "dob", "nationality", "url"]]

In [64]:
# Clean qualifying
qualifying.dtypes
#qualifying["q1"] = qualifying["q1"].replace(["\\N"], [np.nan])
#qualifying["q2"] = qualifying["q2"].replace(["\\N"], [np.nan])
#qualifying["q3"] = qualifying["q3"].replace(["\\N"], [np.nan])
qualifying["q1"] = pd.to_datetime(qualifying["q1"], format="%I:%M.%l")

ValueError: 'l' is a bad directive in format '%I:%M.%l'

In [9]:
display(results)
results.dtypes

,resultId,raceId,driverId,constructorId,number,grid,position,positionText,positionOrder,points,laps,time,milliseconds,fastestLap,rank,fastestLapTime,fastestLapSpeed,statusId
0,1,18,1,1,22,1,1,1,1,10.0,58,1:34:50.616,5690616,39,2,1:27.452,218.300,1
1,2,18,2,2,3,5,2,2,2,8.0,58,+5.478,5696094,41,3,1:27.739,217.586,1
2,3,18,3,3,7,7,3,3,3,6.0,58,+8.163,5698779,41,5,1:28.090,216.719,1
3,4,18,4,4,5,11,4,4,4,5.0,58,+17.181,5707797,58,7,1:28.603,215.464,1
4,5,18,5,1,23,3,5,5,5,4.0,58,+18.014,5708630,43,1,1:27.418,218.385,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25835,25841,1096,854,210,47,12,16,16,16,0.0,57,\N,\N,39,12,1:29.833,211.632,11
25836,25842,1096,825,210,20,16,17,17,17,0.0,57,\N,\N,40,20,1:31.158,208.556,11
25837,25843,1096,1,131,44,5,18,18,18,0.0,55,\N,\N,42,11,1:29.788,211.738,9
25838,25844,1096,849,3,6,20,19,19,19,0.0,55,\N,\N,45,14,1:30.309,210.517,130
25839,25845,1096,4,214,14,10,\N,R,20,0.0,27,\N,\N,24,17,1:30.579,209.889,47

resultId             int64
raceId               int64
driverId             int64
constructorId        int64
number              object
grid                 int64
position            object
positionText        object
positionOrder        int64
points             float64
laps                 int64
time                object
milliseconds        object
fastestLap          object
rank                object
fastestLapTime      object
fastestLapSpeed     object
statusId             int64
dtype: object

In [24]:
drivers.to_csv("data_clean/drivers.csv")

In [35]:
# Number unique drivers
drivers.to_sql('drivers_sql', 
                con = con, 
                if_exists='replace')

857

In [46]:
# Number unique drivers
results.dtypes

resultId             int64
raceId               int64
driverId             int64
constructorId        int64
number              object
grid                 int64
position            object
positionText        object
positionOrder        int64
points             float64
laps                 int64
time                object
milliseconds        object
fastestLap          object
rank                object
fastestLapTime      object
fastestLapSpeed     object
statusId             int64
dtype: object